Create login window
Ovsyanka83/online_chat pull request #7
Opened 2022-09-15 19:05 UTC by VarlaamGraime

2022-09-15 19:17 UTC, Ovsyanka83 requested changes
OK overall but need to fix a few minor things.

2022-09-15 19:17 UTC, Ovsyanka83 commented on frontend/src/Components/UI/Button/MyButton.jsx
> +        console.log('Проверка работы функции')
No console.logs in main branch

2022-09-15 19:17 UTC, Ovsyanka83 commented on frontend/src/Components/UI/Button/MyButton.jsx
> +        console.log({ username })
No console.logs in main branch

2022-09-15 19:17 UTC, Ovsyanka83 commented on frontend/src/Components/UI/Button/MyButton.jsx
> +        // .then(response => response.json())
No commented out code in main branch

2022-09-15 19:17 UTC, Ovsyanka83 commented on frontend/src/Components/UI/Input/MyInput.jsx
> +    // submit from form
There is no form. Please, remove old comments

2022-09-15 19:17 UTC, Ovsyanka83 commented on frontend/src/Components/UI/Input/MyInput.module.css
> +.myInput {
Use better naming for the input

2022-09-15 19:17 UTC, Ovsyanka83 commented on frontend/src/Components/EnterWindow.jsx
> +                {/* transfer of components */}
Wtf is that comment? Why do you need it?

2022-09-15 19:33 UTC, Ovsyanka83 commented on frontend/src/Components/UI/Input/MyInput.module.css
> +.myInput {
Fix this as well

2022-09-16 16:26 UTC, maks-pavlenkov commented on frontend/src/Components/UI/Button/StartChatButton.jsx
> +                name: { nickname }
I am expecting a json with a value named nickname as well. So it would be like this { "nickname": nickname}

2022-09-16 16:32 UTC, VarlaamGraime commented on frontend/src/Components/UI/Button/StartChatButton.jsx
> +                name: { nickname }
fix

2022-09-16 16:32 UTC, VarlaamGraime commented on frontend/src/Components/UI/Input/MyInput.module.css
> +.myInput {
ok

2022-09-16 16:39 UTC, maks-pavlenkov approved these changes

2022-09-16 16:39 UTC, Ovsyanka83 approved these changes

2022-09-16 16:40 UTC, merged